language: cpp
dist: bionic
compiler: gcc
cache: pip
env:
  - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - sudo apt update
  - sudo apt install build-essential cmake gfortran locales zlib1g-dev liblzma-dev
  - sudo apt install python3 python3-setuptools python3-pip python3-virtualenv
  - sudo locale-gen en_US.UTF-8
  - sudo pip3 install cget
  - cget install -f requirements.txt
install:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cget/cget/cget.cmake -DBUILD_TESTS=1 ..
  - make
  - cd ..
script:
  - build/raremetal/tests/bin/tests-raremetal
